### ISSUE TITLE
Listening on INADDR6_ANY not possible

### ISSUE THREAD

**Issue by Grimeton** [coder/code-server#1582]
Hi,

when starting the server while trying to listen on INADDR6_ANY, also known as "::", the server errors out. It's not accepting a simple "::". According to RFC4038 the addresses should be placed in brackets, even when not using a port, so the "::" turns into "[::]", doesn't work either.

After switching to the --bind-addr parameter the situation got worse, because now, using "::" together with a port isn't possible anymore. When following RFC4038 I'm neither able to use "[::]", nor "[::]:1234".

Same happens with INADDR6_LOOPBACK, e.g. "::1" or "[::1]" or "[::1]:1234".

KR,

G.

**Comment by nhooyr** [comment]
Nice catch!

**Comment by code-asher** [comment]
Fixed and will be in 3.6.0.

**Comment by cycl0ne** [comment]
still not working or im not using the config.yaml correct, got the same errors with bind-addr: 

Running with 3.10.2

**Comment by code-asher** [comment]
@cycl0ne something like this should work:

```
bind-addr: "[1234:1234:1234::1234]:443"
```

If it doesn't could you open a new issue with the `bind-addr` line you are trying to use and the code-server output? Thanks!

**Comment by despiegk** [comment]
```
root@vm1:~# code-server --host ::
[2022-01-08T03:16:47.810Z] info  code-server 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc
[2022-01-08T03:16:47.812Z] info  Using user-data-dir ~/.local/share/code-server
[2022-01-08T03:16:47.834Z] error Invalid URL: http://:::8080
```

```
root@vm1:~# code-server --host "[::]:8080"
[2022-01-08T03:17:02.380Z] info  code-server 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc
[2022-01-08T03:17:02.383Z] info  Using user-data-dir ~/.local/share/code-server
[2022-01-08T03:17:02.425Z] error getaddrinfo ENOTFOUND ::]:808
```

doesn't work for me

**Comment by jsjoeio** [comment]
cc @code-asher - any ideas?^

**Comment by code-asher** [comment]
Actually there is a `family` property we can use to see if it is IPv6.

**Comment by qiurigao** [comment]
It still does not work for me. Using version 4.3.0
