### ISSUE TITLE
Abnormal white blank when inputting in ipad

### ISSUE THREAD

**Issue by xcpky** [coder/code-server#5391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: ipad OS 16
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.5.1

### Steps to Reproduce

1. enter code server in safari
2. click anywhere that requires input
3. an abnormal white blank appears in the bottom

### Expected

there should be no white blank

### Actual

there is an white blank

### Screenshot/Video

![7F11AFE0-B1C9-4D8D-8489-51458F056B24](https://user-images.githubusercontent.com/52552971/181933739-b1d61864-1e62-420a-b627-e074e306126a.png)
![Uploading AC740DB2-95B8-44F2-8D67-F8FDBCE5A370.png…]()

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I guess it has something to do with the input method. After I press the floating input icon, which cause it to expand in the mid bottom, and drag it to the right bottom, the white blank disappeared, (shown in the video I uploaded)

https://user-images.githubusercontent.com/52552971/181933960-1980843f-29f7-4eda-aa21-3639f8464e68.MOV

.

**Comment by hzb-ykpcx** [comment]
seems like an ipad os 16 bug after using stage manager

**Comment by jsjoeio** [comment]
Can you reproduce on github.dev?

**Comment by hzb-ykpcx** [comment]
No, I can't reproduce it in github.dev

**Comment by hzb-ykpcx** [comment]
> seems like an ipad os 16 bug after using stage manager

The same issue exists without using stage manager.

**Comment by jsjoeio** [comment]
Darn it! We'll have to investigate further.

You could also try reproducing on Codespaces if you have access

**Comment by mohdali** [comment]
Same issue happens in Codespaces. If I move the input method button around it disappears. Very annoying indeed.

**Comment by jsjoeio** [comment]
@mohdali do you mind opening an issue in microsoft/vscode? Sounds like it's upstream then.

**Comment by mohdali** [comment]
Seems the issue was resolved in the latest iPadOS beta, I'm no longer able to reproduce.

**Comment by hzb-ykpcx** [comment]
> Seems the issue was resolved in the latest iPadOS beta, I'm no longer able to reproduce.

I can still reproduce the issue in the latest iPadOS beta 16.1

**Comment by jsjoeio** [comment]
@hzb-ykpcx does it happen in Codespaces for you?

**Comment by hzb-ykpcx** [comment]
sry, but I don't have codespaces.

**Comment by jsjoeio** [comment]
how about vscode.dev?

**Comment by hzb-ykpcx** [comment]
I solved the issue by reopen the stage manager, after updating to the latest ipad OS 16 beta , thx.

**Comment by magneter** [comment]
hi,I tried many time ,the problem still there.
ipad os:16.1
code-server:  1.72.1
macos:ventura13.0
mac: 2019 15inch intel i9

**Comment by hzb-ykpcx** [comment]
I found the previous workaround not working anymore recently as well, so now reopen

**Comment by jsjoeio** [comment]
What version of iPad are you both using?

**Comment by hzb-ykpcx** [comment]
I am using iPadOS 16.2, and a friend of mine using 15.x meets the problem as well.

**Comment by magneter** [comment]
I used ipados 16.1 and macos 13.1 .
I upgrade the ipados to 16.2, and the problem still there.

**Comment by magneter** [comment]
@hzb-ykpcx have you  found some solutions?
I found the related issue. In this issue, disable shortcuts should work , but trackpad also  not work
https://github.com/microsoft/vscode/issues/149048

**Comment by TUCAOEVER** [comment]
I got the same issue.

**Comment by TUCAOEVER** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by stebiru** [comment]
I had the same problem. Issue seems to be related to "shortcut" in keyboard settings.  
See the right box on the bottom with  the "EN" inside, in the image you posted.
 
Turning off shortcuts on your iPad in Settings -> General -> Keyboard, that will remove the white bar.

**Comment by TUCAOEVER** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by code-asher** [comment]
Closing, see the linked issue upstream.
